  require('dotenv').config()

export default {
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,
  DATABASE: process.env.DATABASE,
  DATABASE_HOST: process.env.DATABASE_HOST,
  DATABASE_PORT: process.env.DATABASE_PORT,
  DATABASE_USERNAME: process.env.DATABASE_USERNAME,
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  DATABASE_NAME: process.env.DATABASE_NAME,
  TYPEORM_SEEDING_FACTORIES: process.env.TYPEORM_SEEDING_FACTORIES,
  TYPEORM_SEEDING_SEEDS: process.env.TYPEORM_SEEDING_SEEDS,
  TYPEORM_SEEDING_MIGRATIONS: process.env.TYPEORM_SEEDING_MIGRATIONS,
}